name: 'Shortcut release notes github action'
description: "Scienta's take on release notes using Shortcut"
author: 'Scienta'
inputs:
  github-token:
    description: 'Github Actions Token or Personal Access Token (PAT)'
    required: true
  clubhouse-token:
    description: 'Shortcut token, name for BC reasons'
    required: true
  repository-owner:
    description: 'Owner of the repository'
    required: true
  repository-name:
    description: 'Name of the repository'
    required: true
  releasenotes-template:
    description: 'ejs template to render the release notes'
    required: true
  no-stories-template:
    description: 'ejs template to render when no stories are found'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
