version: "3.8"
services:
  node:
    container_name: clubhouse-releasenotes-github-action
    image: "node:12"
    working_dir: /home/node/app
    environment:
      NODE_ENV: development
      INPUT_GITHUB-TOKEN: "${GITHUB_TOKEN}"
      INPUT_CLUBHOUSE-TOKEN: "${CLUBHOUSE_TOKEN}"
      GITHUB_EVENT_PAYLOAD: "${GITHUB_EVENT_PAYLOAD}"
      INPUT_REPOSITORY-OWNER: "${REPOSITORY_OWNER}"
      INPUT_REPOSITORY-NAME: "${REPOSITORY_NAME}"
      INPUT_RELEASENOTES-TEMPLATE: "${RELEASENOTES_TEMPLATE}"
      INPUT_NO-STORIES-TEMPLATE: "${NO_STORIES_TEMPLATE}"
    volumes:
      - ./:/home/node/app
    command: "tail -f /dev/null"
